### ISSUE TITLE
when i change the <br>, all parts and after it disappeared!

### ISSUE THREAD

**Issue by fakefish** [iSimar/ParseHTML-React-Native#1]
`'<br>' : {marginBottom:5}`
like this
is it a bug?

**Comment by fakefish** [comment]
and seems the margin and padding didnot works!

**Comment by fakefish** [comment]
and before `<p>` there should no blank there
![image](https://cloud.githubusercontent.com/assets/1334025/7163766/5f399624-e3ce-11e4-8787-7281a64c0c38.png)
but I cannot fix it! can you help me ?

**Comment by iSimar** [comment]
I'm looking into this.

**Comment by fakefish** [comment]
did not spport `<img>` ?

**Comment by iSimar** [comment]
Open tags like:

```
Hello<br>World
```

Don't seem to be working at the moment at, I will implement that function along with marginBottom and padding.
For a quick/temporary fix you can do:

```
Hello<br></br>World
```

I have fixed the `<p>` bug.

A lot of tags do not work - the project is still at a very early stage.

**Comment by fakefish** [comment]
can you make a config file to others like me could pull request?
